// <auto-generated />
using System;
using IzinTakipVeOnaySistemi.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IzinTakipVeOnaySistemi.DAL.Migrations
{
    [DbContext(typeof(IzinTakipOnayDbContext))]
    [Migration("20250621102852_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktiflikDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("EpostaAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IzinSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktiflikDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.IzinTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktiflikDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IzinBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IzinBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdemeBilgisiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalepDurumu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("OdemeBilgisiId")
                        .IsUnique();

                    b.ToTable("IzinTalepler");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.OdemeBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktiflikDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OdenecekTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OdemeBilgileri");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.Calisan", b =>
                {
                    b.HasOne("IzinTakipVeOnaySistemi.DAL.Entities.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.IzinTalep", b =>
                {
                    b.HasOne("IzinTakipVeOnaySistemi.DAL.Entities.Calisan", "Calisan")
                        .WithMany("IzinTalepleri")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IzinTakipVeOnaySistemi.DAL.Entities.OdemeBilgisi", "OdemeBilgisi")
                        .WithOne("IzinTalep")
                        .HasForeignKey("IzinTakipVeOnaySistemi.DAL.Entities.IzinTalep", "OdemeBilgisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("OdemeBilgisi");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.Calisan", b =>
                {
                    b.Navigation("IzinTalepleri");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.Departman", b =>
                {
                    b.Navigation("Calisanlar");
                });

            modelBuilder.Entity("IzinTakipVeOnaySistemi.DAL.Entities.OdemeBilgisi", b =>
                {
                    b.Navigation("IzinTalep")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
